---
env:
  global:
    - builddir=./build-CI
    - RELEASE_TESTING=1
    - AUTOMATED_TESTING=1
    - EXTENDED_TESTING=1
    - AUTHOR_TESTING=1
before_install:
  - "export stableperl=`perlbrew list | tail -1`"
  - perlbrew list
  - "perlbrew exec --with $stableperl 'cpanm --quiet --notest --skip-satisfied Pod::Weaver::Section::Support Test::Pod Text::Autoformat Dist::Zilla'"
  - "perlbrew exec --with $stableperl 'dzil authordeps | cpanm --quiet --notest --skip-satisfied'"
  - "perlbrew exec --with $stableperl 'dzil listdeps --author  | cpanm --notest --skip-satisfied'"
  - "perlbrew exec --with $stableperl 'dzil build --in $builddir'"

install:
  - '(cd $builddir && cpanm --quiet --notest --installdeps --skip-satisfied .)'
  - cpanm --notest --skip-satisfied Test::CPAN::Changes Test::Kwalitee Test::TrailingSpace
  
language: perl
perl:
  - '5.8'
  - '5.10'
  - '5.12'
  - '5.14'
  - '5.16'
  - '5.18'
  - '5.20'
  - '5.22'
  - '5.24'
  - '5.26'
  - '5.28'
script:
   - '(cd $builddir && prove -lr t)'
